<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_quote-filter-faux-input</name>
   <tag></tag>
   <elementGuidId>d02b13c2-63ee-47cf-a75e-27941da5f6e0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quote-filter-faux-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>bestSellers-clear-</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-quote-filters&quot;)/div[@class=&quot;quote-filter-section&quot;]/div[1]/ul[@class=&quot;quote-filter-options&quot;]/li[2]/label[@class=&quot;quote-filter-faux-input&quot;]</value>
   </webElementProperties>
</WebElementEntity>
