<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Apply for This Plan</name>
   <tag></tag>
   <elementGuidId>7b7d0ba2-3a10-4332-b767-6f8b412854d7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plan-details-primary-apply</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics</name>
      <type>Main</type>
      <value>{&quot;census&quot;:{&quot;isCanonical&quot;:false,&quot;dentalIsCanonical&quot;:true,&quot;oneTimePaymentSelected&quot;:false,&quot;stIndeterminateContractLength&quot;:true,&quot;planYear&quot;:2015,&quot;member&quot;:[{&quot;role&quot;:&quot;P&quot;,&quot;age&quot;:48,&quot;smoker&quot;:false,&quot;gender&quot;:&quot;M&quot;,&quot;dob&quot;:&quot;1969-12-21&quot;,&quot;eligible&quot;:true}],&quot;dentalEffective&quot;:&quot;2018-09-01T04:00:00.000Z&quot;,&quot;effective&quot;:&quot;2018-09-01T04:00:00.000Z&quot;,&quot;maxEffectiveEnd&quot;:null,&quot;location&quot;:{&quot;zip&quot;:&quot;35215&quot;,&quot;state&quot;:&quot;AL&quot;,&quot;county&quot;:&quot;Jefferson&quot;,&quot;fips&quot;:&quot;01073&quot;,&quot;_id&quot;:{&quot;_bsontype&quot;:&quot;ObjectID&quot;,&quot;id&quot;:{&quot;type&quot;:&quot;Buffer&quot;,&quot;data&quot;:[90,204,84,82,200,52,135,60,78,141,192,69]}},&quot;fullCodeList&quot;:[&quot;01360&quot;],&quot;code&quot;:&quot;01360&quot;,&quot;maRegionCode&quot;:&quot;10&quot;,&quot;pdpRegionCode&quot;:&quot;12&quot;,&quot;ifpRegionCode&quot;:&quot;3&quot;,&quot;defaultedCounty&quot;:false,&quot;city&quot;:&quot;Birmingham&quot;,&quot;stateName&quot;:&quot;Alabama&quot;},&quot;effectiveEnd&quot;:&quot;2018-11-30T05:00:00.000Z&quot;},&quot;plan&quot;:{&quot;_id&quot;:&quot;5b835b73d8e8e3065c07e06e&quot;,&quot;waitingPeriodForIllnesses&quot;:5,&quot;familyMoopIncludesDeductible&quot;:false,&quot;moopIncludesDeductible&quot;:true,&quot;officeVisit&quot;:&quot;&quot;,&quot;internationalCoverageURL&quot;:&quot;&quot;,&quot;internationalCoverageDetail&quot;:&quot;&quot;,&quot;internationalCoverage&quot;:&quot;No&quot;,&quot;oonCoverage&quot;:true,&quot;primaryCareBenefitURL&quot;:&quot;&quot;,&quot;primaryCareServiceBenefit&quot;:false,&quot;referralsRequired&quot;:false,&quot;primaryCarePhysicianRequired&quot;:false,&quot;maternity&quot;:false,&quot;periodicObGyn&quot;:false,&quot;periodicHealthExam&quot;:false,&quot;wellBabyCare&quot;:false,&quot;planType&quot;:&quot;PPO&quot;,&quot;planName&quot;:&quot;LifeShield Flex 5000/20/9000/750000&quot;,&quot;planSubType&quot;:&quot;lite&quot;,&quot;carrierId&quot;:&quot;lifeshield&quot;,&quot;deliveryHospital&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not Covered&quot;},&quot;preAndPostNatal&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not Covered&quot;},&quot;hospitalization&quot;:{&quot;amount&quot;:1,&quot;message&quot;:&quot;Average Standard Room Rate: $1,000 per day. Hospital ICU: $1,250 per day&quot;},&quot;outpatient&quot;:{&quot;amount&quot;:1,&quot;message&quot;:&quot;Facility charges up to a max of $1,250 per day; $5,000 Surgeon and $1,000 Assistant Surgeon limitations apply&quot;},&quot;emergency&quot;:{&quot;amount&quot;:24,&quot;message&quot;:&quot;Emergency Room (This includes the emergency room physician charge, 24 hours surveillance and all miscellaneous medical charges) The benefit payable for each emergency room visit, including professional and facility services, will not exceed $250 per visit.&quot;},&quot;labXray&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not Covered&quot;},&quot;rxDeductible&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not covered except those administered by a Doctor in an Inpatient or Outpatient setting covered under this Policy as an Eligible Expense.&quot;},&quot;rxNonFormulary&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not covered except those administered by a Doctor in an Inpatient or Outpatient setting covered under this Policy as an Eligible Expense.&quot;},&quot;rxBrand&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not covered except those administered by a Doctor in an Inpatient or Outpatient setting covered under this Policy as an Eligible Expense.&quot;},&quot;rxGeneric&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not covered except those administered by a Doctor in an Inpatient or Outpatient setting covered under this Policy as an Eligible Expense.&quot;},&quot;mentalHealth&quot;:{&quot;amount&quot;:100,&quot;message&quot;:&quot;Inpatient: $100 per day, 31 day maximum per Covered Person per Coverage Period. Outpatient: $50 per visit, 10 visits per Covered Person per Coverage Period&quot;},&quot;chiropractic&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not Covered&quot;},&quot;wellBaby&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not Covered&quot;},&quot;obGynExam&quot;:{&quot;amount&quot;:0,&quot;message&quot;:&quot;Not Covered&quot;},&quot;periodicExam&quot;:{&quot;amount&quot;:50,&quot;message&quot;:&quot;Covered - member pays $50 copay, benefit is not subject to deductible or coinsurance.&quot;},&quot;specialist&quot;:{&quot;amount&quot;:30,&quot;message&quot;:&quot;$30 Copayment per visit per Covered Person not to exceed a maximum of 3 Copayments per Covered Person. Eligible Expenses and benefits are not subject to the Plan Deductible or Coinsurance. Office Visits in excess of the maximum number of Copayments will be subject to the Plan Deductible and Coinsurance.&quot;},&quot;primaryDoctorVisit&quot;:{&quot;amount&quot;:30,&quot;message&quot;:&quot;$30 Copayment per visit per Covered Person not to exceed a maximum of 3 Copayments per Covered Person. Eligible Expenses and benefits are not subject to the Plan Deductible or Coinsurance. Office Visits in excess of the maximum number of Copayments will be subject to the Plan Deductible and Coinsurance.&quot;},&quot;coinsurance&quot;:20,&quot;deductibleTotalingType&quot;:&quot;&quot;,&quot;maxDeductibleLimits&quot;:3,&quot;familyDeductibleType&quot;:&quot;M&quot;,&quot;maxOOPLimits&quot;:3,&quot;familyMoopType&quot;:&quot;M&quot;,&quot;__v&quot;:0,&quot;planId&quot;:&quot;lifeshield-flex-al-5000-20-9000-750000&quot;,&quot;providerInfo&quot;:{&quot;_id&quot;:&quot;58b627a6de34940400e01519&quot;,&quot;updated&quot;:&quot;2017-07-06T05:36:33.093Z&quot;,&quot;uri&quot;:&quot;lifeshield-4icyj&quot;,&quot;lastUpdatedBy&quot;:&quot;Beck Lin&quot;,&quot;hpId&quot;:&quot;lifeshield&quot;,&quot;displayName&quot;:&quot;LifeShield&quot;,&quot;logoFile&quot;:&quot;http://stratos.healthpocket.com/lifeshield-8026365c4d6c5ebcef0cc620b6223217.png&quot;,&quot;url&quot;:&quot;&quot;,&quot;__v&quot;:0,&quot;created&quot;:&quot;2017-03-01T01:45:10.273Z&quot;,&quot;sourceNames&quot;:[&quot;LifeShield&quot;],&quot;companyName&quot;:[{&quot;name&quot;:&quot;LifeShield National Insurance Co.&quot;,&quot;_id&quot;:&quot;595dcc61908b4800048314d6&quot;,&quot;state&quot;:&quot;ALL&quot;}],&quot;productLines&quot;:[&quot;ST&quot;],&quot;states&quot;:[]},&quot;breakdown&quot;:{&quot;applicant&quot;:88.05,&quot;spouse&quot;:0,&quot;children&quot;:0,&quot;tax&quot;:1,&quot;baseRate&quot;:88.05,&quot;fees&quot;:{&quot;medsense&quot;:{&quot;id&quot;:&quot;medsense&quot;,&quot;amount&quot;:19.99,&quot;_id&quot;:&quot;5b835b73d8e8e3065c07e01b&quot;,&quot;kind&quot;:&quot;R&quot;}},&quot;monthlyCost&quot;:108.03999999999999,&quot;initialCost&quot;:108.03999999999999,&quot;totalRecurringFee&quot;:19.99},&quot;deductible&quot;:5000,&quot;externalPlanId&quot;:137,&quot;coinsuranceLimit&quot;:20000,&quot;companyName&quot;:&quot;LifeShield National Insurance Co.&quot;,&quot;lifetimeMax&quot;:750000,&quot;moop&quot;:9000,&quot;outOfPocketMax&quot;:9000,&quot;maxDurationMonths&quot;:3,&quot;extended&quot;:false,&quot;daily&quot;:false,&quot;familyDeductible&quot;:15000,&quot;familyMoop&quot;:27000,&quot;minEffectiveDate&quot;:&quot;2018-09-01T04:00:00.000Z&quot;,&quot;effectiveEnd&quot;:&quot;2018-11-30T05:00:00.000Z&quot;,&quot;maxEffectiveEnd&quot;:&quot;2018-11-30T05:00:00.000Z&quot;,&quot;coverageDurationPeriod&quot;:3,&quot;logoFile&quot;:&quot;http://stratos.healthpocket.com/lifeshield-8026365c4d6c5ebcef0cc620b6223217.png&quot;,&quot;hasFees&quot;:true},&quot;productLine&quot;:&quot;Short Term&quot;}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-lg apply-btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/term-health-insurance/apply/lifeshield-flex-al-5000-20-9000-750000</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply for This Plan</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plan-details-primary-apply&quot;)</value>
   </webElementProperties>
</WebElementEntity>
